#!/bin/bash

start=`date +%s.%N`

for file in `git ls-files |grep -P "(\.xml)|(\.java)|(\.md)|(\.gradle)"`; do git blame --line-porcelain $file|sed -n 's/^author //p'; done |sort |uniq -c |sort -rn

end=`date +%s.%N`
echo 统计共耗时`echo "$end - $start" |bc -l`秒
